name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and install Python dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Download Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager
          echo "SDKManager version:"
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --version

      - name: Install Android SDK Build Tools and Platform Tools
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH
          yes | sdkmanager --sdk_root=$HOME/android-sdk \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-34" \
            "emulator" \
            "tools"
        shell: bash

      - name: Accept Android SDK licenses
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | sdkmanager --licenses --sdk_root=$HOME/android-sdk
        shell: bash

      - name: Build APK
        run: |
          buildozer android debug

      - name: List build outputs
        run: ls -la bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
