name: Build APK (No Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools python3-wheel \
            git zip unzip openjdk-17-jdk \
            build-essential ccache libncurses5-dev \
            libstdc++6 libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev zlib1g-dev libpng-dev wget

      - name: Install Buildozer + Python deps
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer

      - name: Install Android SDK & NDK
        env:
          ANDROID_HOME: /usr/lib/android-sdk
          ANDROID_SDK_ROOT: /usr/lib/android-sdk
        run: |
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          sudo unzip -q cmdline-tools.zip -d /usr/lib/android-sdk/cmdline-tools
          sudo mv /usr/lib/android-sdk/cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest
          yes | sudo /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/lib/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;21.4.7075529"

      - name: Build APK
        env:
          ANDROIDSDK: /usr/lib/android-sdk
          ANDROIDNDK: /usr/lib/android-sdk/ndk/21.4.7075529
          ANDROID_HOME: /usr/lib/android-sdk
          ANDROID_SDK_ROOT: /usr/lib/android-sdk
        run: |
          echo "✅ Android SDK installed at $ANDROIDSDK"
          echo "✅ NDK installed at $ANDROIDNDK"
          buildozer -v android debug

      - name: List build outputs
        run: ls -la bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
