name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            curl \
            wget

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Set up Android SDK correctly
        run: |
          # Clean up any existing directories
          rm -rf ~/.android
          rm -rf ~/.buildozer
          
          # Create proper directory structure
          mkdir -p ~/android-sdk/cmdline-tools/latest
          
          # Download Android Command Line Tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp/
          
          # Move to correct location with proper structure
          mv /tmp/cmdline-tools/* ~/android-sdk/cmdline-tools/latest/
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          # Set SDK root explicitly
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          
          # Accept licenses
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses || true
          
          # Install components with explicit SDK root
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "build-tools;34.0.0"
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools"
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-34"
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "ndk;23.2.8568313"

      - name: Update Buildozer spec to use our SDK
        run: |
          if [ -f "buildozer.spec" ]; then
            # Update Android settings
            sed -i 's/android.api = .*/android.api = 34/' buildozer.spec
            sed -i 's/android.minapi = .*/android.minapi = 24/' buildozer.spec
            sed -i 's/android.ndk = .*/android.ndk = 23.2.8568313/' buildozer.spec
            sed -i 's|#android.sdk_path =.*|android.sdk_path = /home/runner/android-sdk|' buildozer.spec
            sed -i 's|#android.ndk_path =.*|android.ndk_path = /home/runner/android-sdk/ndk/23.2.8568313|' buildozer.spec
          fi

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
