name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libstdc++6 \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            python3-pip \
            curl \
            wget

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Set up Android SDK with correct structure
        run: |
          # Clean up any existing directories
          rm -rf ~/.buildozer/android/platform/android-sdk
          
          # Create directory structure that Buildozer expects
          mkdir -p ~/.buildozer/android/platform/android-sdk
          
          # Download Android Command Line Tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp/
          
          # Move to the location Buildozer expects (tools directory)
          mv /tmp/cmdline-tools ~/.buildozer/android/platform/android-sdk/tools
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/.buildozer/android/platform/android-sdk/tools/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          # Accept licenses first
          yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses
          
          # Install required components
          $ANDROID_SDK_ROOT/tools/bin/sdkmanager \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-34" \
            "ndk;23.2.8568313"

      - name: Update Buildozer spec to use correct SDK path
        run: |
          if [ -f "buildozer.spec" ]; then
            # Update Android settings
            sed -i 's/android.api = .*/android.api = 34/' buildozer.spec
            sed -i 's/android.minapi = .*/android.minapi = 24/' buildozer.spec
            sed -i 's/android.ndk = .*/android.ndk = 23.2.8568313/' buildozer.spec
            sed -i 's|#android.sdk_path =.*|android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk|' buildozer.spec
            sed -i 's|#android.ndk_path =.*|android.ndk_path = /home/runner/.buildozer/android/platform/android-sdk/ndk/23.2.8568313|' buildozer.spec
          fi

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
