name: Build APK (No Docker, sdkmanager + AIDL fixed)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a version compatible with Buildozer

      - name: Install Buildozer & Python dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Verify buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "❌ buildozer.spec missing in repo root!"
            ls -la
            exit 1
          fi
          echo "✅ buildozer.spec found"

      - name: Build APK
        run: |
          buildozer -v android debug
      
      - name: List build outputs
        run: ls -la bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
