name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install Buildozer & Python dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Install Android SDK Build Tools
        run: |
          yes | sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"
        env:
          ANDROID_SDK_ROOT: ${{ runner.home }}/.buildozer/android/platform/android-sdk

      - name: Build APK
        run: |
          buildozer android debug
      
      - name: List build outputs
        run: ls -la bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
