name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use Python 3.11 for compatibility

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer[full]

    - name: Build Android APK
      run: |
        buildozer android debug
