name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libstdc++6 \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            python3-pip \
            curl \
            wget

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Set up Android SDK correctly
        run: |
          # Create Android SDK directory structure
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          
          # Download Android Command Line Tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d /tmp/
          
          # Move to correct location (FIXED PATH)
          mv /tmp/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          # Accept licenses first
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          
          # Install required components
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-34" \
            "ndk;23.2.8568313"

      - name: Verify Android tools
        run: |
          echo "Android SDK contents:"
          ls -la $ANDROID_SDK_ROOT/
          echo "Command line tools:"
          ls -la $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
          echo "AIDL location:"
          find $ANDROID_SDK_ROOT -name "aidl" -type f 2>/dev/null | head -5 || echo "AIDL not found yet"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
