name: Build APK (No Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools python3-wheel \
            git zip unzip openjdk-17-jdk \
            build-essential ccache libncurses5 \
            libstdc++6 libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev zlib1g-dev libpng-dev

      - name: Install Buildozer + dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer

      - name: Verify buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "❌ buildozer.spec missing in repo root!"
            exit 1
          fi
          echo "✅ buildozer.spec found"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: List build outputs
        run: ls -la bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
